# Generated by Django 4.0.3 on 2023-06-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookletstackweb', '0006_rename_username_userdetails_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
