# Generated by Django 4.0.3 on 2023-06-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookletstackweb', '0007_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
